const routes=[{from:"永康",to:"保安",blessing:"永遠平安健康",fromRoman:"Yongkang",toRoman:"Baoan"},{from:"追分",to:"成功",blessing:"努力追分，終會成功",fromRoman:"Zhuifen",toRoman:"Chenggong"},{from:"榮華",to:"富貴",blessing:"富貴順遂，好運常在",fromRoman:"Ronghua",toRoman:"Fugui"},{from:"加祿",to:"東海",blessing:"加官晉祿，福運東來",fromRoman:"Jialu",toRoman:"Donghai"},{from:"吉安",to:"壽豐",blessing:"吉祥平安，福壽豐盛",fromRoman:"Jian",toRoman:"Shoufeng"},{from:"多良",to:"金崙",blessing:"良緣常伴，金運相隨",fromRoman:"Duoliang",toRoman:"Jinlun"},{from:"成功",to:"歸來",blessing:"成功歸來，平安常在",fromRoman:"Chenggong",toRoman:"Guilai"},{from:"后里",to:"成功",blessing:"心想事成，成功抵達",fromRoman:"Houli",toRoman:"Chenggong"},{from:"苑里",to:"成功",blessing:"一路順遂，終得成功",fromRoman:"Yuanli",toRoman:"Chenggong"},{from:"十分",to:"幸福",blessing:"十分幸福，甜蜜圓滿",fromRoman:"Shifen",toRoman:"Xingfu"}];
const fallbackRoman={永康:"Yongkang",保安:"Baoan",追分:"Zhuifen",成功:"Chenggong",榮華:"Ronghua",富貴:"Fugui",加祿:"Jialu",東海:"Donghai",吉安:"Jian",壽豐:"Shoufeng",多良:"Duoliang",金崙:"Jinlun",歸來:"Guilai",后里:"Houli",苑里:"Yuanli",十分:"Shifen",幸福:"Xingfu"};
const $=id=>document.getElementById(id);const state={manualBlessing:false};
function fillDate(){for(let y=2024;y<=2035;y++)$("year").append(new Option(`${y} 年`,y));for(let m=1;m<=12;m++)$("month").append(new Option(`${String(m).padStart(2,"0")} 月`,m));for(let d=1;d<=31;d++)$("day").append(new Option(`${String(d).padStart(2,"0")} 日`,d));$("year").value=2026;$("month").value=1;$("day").value=5}
function fillRoutes(){const fs=new Set,ts=new Set;routes.forEach((r,i)=>{if(!fs.has(r.from)){fromSelect.append(new Option(r.from,i));fs.add(r.from)}if(!ts.has(r.to)){toSelect.append(new Option(r.to,r.to));ts.add(r.to)}})}
function selectedRoute(){return routes[Number(fromSelect.value)]||routes[0]}function bestRouteByPair(f,t){return routes.find(r=>r.from===f&&r.to===t)}
function romanizeStation(name){if(fallbackRoman[name])return fallbackRoman[name];try{const result=window.pinyinPro?.pinyin(name,{toneType:"none",type:"array"});const parts=Array.isArray(result)?result:String(result||"").split(/\s+/);if(parts[0])return parts.map(part=>part.charAt(0).toUpperCase()+part.slice(1)).join("")}catch(error){}return name||"Custom"}
function applyTicketStyle(style){const second=style==="two";paperBase.setAttribute("fill",second?"#f1eadb":"#faf6e9");doodleLayer.setAttribute("opacity",second?"0":"1");fiberLayer.setAttribute("opacity",second?"1":"0");document.querySelectorAll(".style-option").forEach(button=>{const active=button.dataset.style===style;button.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active))});ticketSvg.dataset.style=style}
function setCustomOpen(kind,open){const button=$(`${kind}Toggle`),wrap=$(`${kind}CustomWrap`),input=$(`${kind}Custom`),select=$(`${kind}Select`);button.setAttribute("aria-expanded",String(open));button.querySelector("span").textContent=open?"↩":"＋";button.lastChild.textContent=open?` 返回${kind==="from"?"起點":"終點"}選單`:` 自訂${kind==="from"?"起點":"終點"}`;select.hidden=open;wrap.hidden=!open;if(open)input.focus();else input.value=""}
function syncFromRoute(){const r=selectedRoute();toSelect.value=r.to;fromCustom.value="";toCustom.value="";setCustomOpen("from",false);setCustomOpen("to",false);fromRoman.value=r.fromRoman;toRoman.value=r.toRoman;render()}
function fitText(node,max,min,width){node.style.fontSize=`${max}px`;let s=max;while(node.getComputedTextLength&&node.getComputedTextLength()>width&&s>min){s-=2;node.style.fontSize=`${s}px`}}
function automaticBlessing(from,to,match){if(match)return match.blessing;if(from&&to)return"依然勇敢，常保平安";return"一路順風，平安抵達"}
function render(){const y=year.value,m=String(month.value).padStart(2,"0"),d=String(day.value).padStart(2,"0"),r=selectedRoute(),f=fromCustom.value.trim()||r.from,t=toCustom.value.trim()||toSelect.value||r.to,match=bestRouteByPair(f,t);fromRoman.value=match?.fromRoman||romanizeStation(f);toRoman.value=match?.toRoman||romanizeStation(t);const finalBlessing=blessing.value.trim()||automaticBlessing(f,t,match);dateText.textContent=`${y}.${m}.${d}`;fromText.textContent=f||"起點";toText.textContent=t||"終點";fromRomanText.textContent=fromRoman.value;toRomanText.textContent=toRoman.value;blessingText.textContent=finalBlessing;fitText(fromText,72,44,430);fitText(toText,72,44,430);fitText(fromRomanText,35,20,470);fitText(toRomanText,35,20,470);fitText(blessingText,35,23,560);drawQR(location.href.split("#")[0])}
function drawQR(text){qrGroup.innerHTML="";let bits;if(window.qrcode){const qr=qrcode(0,"M");qr.addData(text);qr.make();bits=Array.from({length:qr.getModuleCount()},(_,y)=>Array.from({length:qr.getModuleCount()},(_,x)=>qr.isDark(y,x)))}else{bits=makePseudoQR(text,29)}const size=236,cell=size/bits.length,bg=document.createElementNS("http://www.w3.org/2000/svg","rect");bg.setAttribute("width",size);bg.setAttribute("height",size);bg.setAttribute("fill","#f8edc7");qrGroup.append(bg);bits.forEach((row,y)=>row.forEach((on,x)=>{if(!on)return;const rect=document.createElementNS("http://www.w3.org/2000/svg","rect");rect.setAttribute("x",(x*cell).toFixed(2));rect.setAttribute("y",(y*cell).toFixed(2));rect.setAttribute("width",Math.ceil(cell));rect.setAttribute("height",Math.ceil(cell));rect.setAttribute("fill","#11100c");qrGroup.append(rect)}))}
function makePseudoQR(text,n){const g=Array.from({length:n},()=>Array(n).fill(false));const finder=(ox,oy)=>{for(let y=0;y<7;y++)for(let x=0;x<7;x++)g[oy+y][ox+x]=x===0||y===0||x===6||y===6||(x>=2&&x<=4&&y>=2&&y<=4)};finder(0,0);finder(n-7,0);finder(0,n-7);let seed=2166136261;for(const ch of text)seed=Math.imul(seed^ch.charCodeAt(0),16777619);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const fixed=(x<8&&y<8)||(x>=n-8&&y<8)||(x<8&&y>=n-8);if(fixed)continue;seed^=seed<<13;seed^=seed>>>17;seed^=seed<<5;g[y][x]=((seed+x*17+y*31)&3)===0||((x+y)%7===0)}return g}
function savePng(){const copy=ticketSvg.cloneNode(true),svgStyle=`<style>.title{font:700 40px DFKai-SB,KaiTi,PMingLiU,serif;letter-spacing:4px}.date{font:800 65px 'Courier New',monospace;letter-spacing:5px}.love,.zone{font:700 39px DFKai-SB,KaiTi,PMingLiU,serif}.local,.roman,.price{font-family:'Courier New',monospace;font-weight:800}.local{font-size:30px}.roman{font-size:35px;letter-spacing:1px}.station{font:800 74px DFKai-SB,KaiTi,PMingLiU,serif;letter-spacing:10px}.direction{font:700 35px DFKai-SB,KaiTi,PMingLiU,serif}.blessing{font:700 36px DFKai-SB,KaiTi,PMingLiU,serif;letter-spacing:4px}.qr-caption{font:700 21px DFKai-SB,KaiTi,PMingLiU,serif}.price{font-size:46px}.valid{font:700 34px DFKai-SB,KaiTi,PMingLiU,serif}.note{font:700 23px DFKai-SB,KaiTi,PMingLiU,serif}</style>`;copy.insertAdjacentHTML("afterbegin",svgStyle);const xml=new XMLSerializer().serializeToString(copy),url=URL.createObjectURL(new Blob([xml],{type:"image/svg+xml;charset=utf-8"})),img=new Image;img.onload=()=>{const c=document.createElement("canvas");c.width=1520;c.height=2640;const ctx=c.getContext("2d");ctx.fillStyle="#faf6e9";ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);const a=document.createElement("a");a.download=`我的島嶼車票-${dateText.textContent}.png`;a.href=c.toDataURL("image/png");a.click()};img.src=url}
fillDate();fillRoutes();syncFromRoute();applyTicketStyle("one");["year","month","day"].forEach(id=>$(id).addEventListener("change",render));fromSelect.addEventListener("change",syncFromRoute);toSelect.addEventListener("change",()=>{setCustomOpen("to",false);render()});["from","to"].forEach(kind=>{$(`${kind}Toggle`).addEventListener("click",()=>{setCustomOpen(kind,$(`${kind}CustomWrap`).hidden);render()});$(`${kind}Custom`).addEventListener("input",render)});document.querySelectorAll(".style-option").forEach(button=>button.addEventListener("click",()=>applyTicketStyle(button.dataset.style)));blessing.addEventListener("input",()=>{state.manualBlessing=blessing.value.trim().length>0;render()});saveBtn.addEventListener("click",savePng);


